POST http://127.0.0.1:8000/subscription/add-location/
Content-Type: application/json

{"location": "10.7579,59.9114"}

###

POST http://127.0.0.1:8000/subscription/add-location/
Content-Type: application/json

{"location": "5.3244,60.3971"}

###

GET http://127.0.0.1:8000/subscription/get/locations/
Content-Type: application/json


###

DELETE http://127.0.0.1:8000/subscription/delete/location/
Content-Type: application/json

{"location": "10.7579,59.9114"}
